module.exports = {
  sampleJob1: {
    company: 'Amazon Corporate LLC',
    job_title: 'Software Development Engineer, New AWS/Alexa Service',
    job_description: 'Alexa and AWS are the two hottest technologies being talked about. How would you like to work on both—at the same time? The Amazon Web Services’ Enterprise Apps team is defining the next big step in a truly digital workspace at the junction of Alexa and AWS and will deliver never before seen levels of user experiences.<br><br>We can’t talk about specifics just yet, but the things we are working on are in response to loud and clear feedback from customers about the daily pain points in the digital workplace. We’re leveraging AWS’ scale, reliability, flexibility, and ease of use, we will offer customers an easy to manage and cost effective solution that solves these pain points with highly innovative technology. We’re working hard to define and build this cool new service and launch it for customers as quickly as possible to get feedback and iterate.<br><br>As a highly skilled software development engineer on our team, you will be responsible for designing, building, and operating key pieces of customer facing functionality. Our team has a very collaborative and high energy environment, and is located in both Seattle and Palo Alto.<br><br> As a developer on our team, you’ll own code end-to-end from design, to development, to deployment, to monitoring and operations. You’ll have a sound understanding of the fundamentals of computer science and practical experience. You’ll work closely with senior technical leaders to build large-scale distributed systems as well as software than runs on end-user devices.',
    basic_qualifications: '<li>BS/MS in Computer Science or related field with 3+ year relevant experience.</li><li>2+ years of experience in a technical role in the industry.</li><li>Shown skill with Java, C++, or equivalent object-oriented programming languages.</li><li>Proven success in solving complex technical challenges and building reliable customer facing systems.</li>',
    preferred_qualifications: '<li>Mobile development experience for Android and iOS.</li><li>Java development experience.</li><li>Web development experience including Javascript and Node.js.</li><li>Familiarity with AWS services like EC2, S3, Dynamo DB, Lambda and API Gateway.</li>',
    location: 'US-WA-Seattle',
    posted_date: '5/4/2017',
    post_url: 'https://us-amazon.icims.com/jobs/518945/software-development-engineer%2c-new-aws-alexa-service/job?iis=Job+Posting&iisn=Indeed+%28Free+Posting%29&mobile=false&width=922&height=1200&bga=true&needsRedirect=false&jan1offset=-480&jun1offset=-420'
  }
}